### PR TITLE
Improved the tests to also open the browser and create a `/demo` command execute this.

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Comment by vorburger** [comment]
@edewit did you notice that this failed to build on GCB not (yet?) because of a missing browser package, but simply timed out waiting for the server not test container to even get ready? Could you please kindly rebase this PR - I suspect that #404 will help to get past this (only first?) problem, and am curious to see if it works or what it fails with after that...

**Comment by edewit** [comment]
```
Platform: linux-x64 (Debian - 11)
Cypress Version: 10.2.0
[FAILED] Your system is missing the dependency: Xvfb
[FAILED] 
[FAILED] Install Xvfb and run Cypress again.
```

**Comment by vorburger** [comment]
> [FAILED] Your system is missing the dependency: Xvfb

@edewit I wonder if this may be as simple as inserting `xvfb` in [`Dockerfile-build`](https://github.com/OASIS-learn-study/minecraft-storeys-maker/blob/develop/Dockerfile-build), like this:

    RUN curl -fsSL https://deb.nodesource.com/setup_17.x | bash - && apt install -y xvfb nodejs && node --version

Do you want to just try?

**Comment by vorburger** [comment]
#386 now also occurs in the CI build logs for this. Might that be the reason for the test failure?

**Comment by edewit** [comment]
#386 is not the reason for this error it happens when a user adds only a command for example `m.cmd('/say hello');` when the script is only one line it can't be executed because `m` is not defined it only gets passed into an effect.

**Comment by vorburger** [comment]
@edewit I forgot where we were with this one... do you want to retry how we can get this to pass the build?

**Comment by edewit** [comment]
We might need to look at this together... I don't see why this "never ends" happens or why the build fails on GCB

**Comment by edewit** [comment]
@vorburger I think i finally fixed this, can you have another look?

**Comment by edewit** [comment]
okay almost I think just one more issue with the sound card:
```
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4745:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
```

**Comment by vorburger** [comment]
- Seems to still fail? Sorry...

**Comment by edewit** [comment]
> * Seems to still fail? Sorry...

Yes I know it's the sound card, but I sorted all the other issues it now stops nicely and no more strange async errors

**Comment by vorburger** [comment]
Would it possibly make sense to "split" this, and have a PR for just the
async fixes, without the headless browser, and then that later? Just a
thought.

**Comment by edewit** [comment]
@vorburger don't know what you mean by split, this PR is now just adding the browser based tests to the mineflayer

**Comment by vorburger** [comment]
@edewit as discussed, I'm closing this, in favour of our (cool, new; thanks!) #429.

**Pull request closed without merging**
